version: "2"
services:
    www:
        build: .
        ports: 
            - "8010:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
    portainer:
        image: portainer/portainer
        command: -H unix:///var/run/docker.sock
        restart: always
        ports:
            - "9010:9000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
    db:
        image: mysql:5.7
        ports: 
            - "3308:3308"
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: benji
            MYSQL_PASSWORD: benji
            MYSQL_ROOT_PASSWORD: benji
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8011:80
        environment:
            MYSQL_USER: benji
            MYSQL_PASSWORD: benji
            MYSQL_ROOT_PASSWORD: benji
volumes:
    persistent:
    portainer_data:
